// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQ1JcpFcLD6U1VW7CPv4CUzNeoEIa8sA',
    appId: '1:315654084941:web:8eb7d8f3dcfba65af43f04',
    messagingSenderId: '315654084941',
    projectId: 'pill-buddy-cpe-nnovators',
    authDomain: 'pill-buddy-cpe-nnovators.firebaseapp.com',
    storageBucket: 'pill-buddy-cpe-nnovators.firebasestorage.app',
    measurementId: 'G-56KPN92DPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQ8kiiGppzoBV-nShZAa3NE_ExsttcW8',
    appId: '1:315654084941:android:c85d6d323ba4d683f43f04',
    messagingSenderId: '315654084941',
    projectId: 'pill-buddy-cpe-nnovators',
    storageBucket: 'pill-buddy-cpe-nnovators.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeb2hmH4MX-6Zm7kKeklUTihLxu-LIXQ4',
    appId: '1:315654084941:ios:e77661780a130b77f43f04',
    messagingSenderId: '315654084941',
    projectId: 'pill-buddy-cpe-nnovators',
    storageBucket: 'pill-buddy-cpe-nnovators.firebasestorage.app',
    iosClientId:
        '315654084941-e7p052adc6uc6hlii5ob6mtmv150qide.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeb2hmH4MX-6Zm7kKeklUTihLxu-LIXQ4',
    appId: '1:315654084941:ios:e77661780a130b77f43f04',
    messagingSenderId: '315654084941',
    projectId: 'pill-buddy-cpe-nnovators',
    storageBucket: 'pill-buddy-cpe-nnovators.firebasestorage.app',
    iosClientId:
        '315654084941-e7p052adc6uc6hlii5ob6mtmv150qide.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIQ1JcpFcLD6U1VW7CPv4CUzNeoEIa8sA',
    appId: '1:315654084941:web:93c09959fcbd2d9df43f04',
    messagingSenderId: '315654084941',
    projectId: 'pill-buddy-cpe-nnovators',
    authDomain: 'pill-buddy-cpe-nnovators.firebaseapp.com',
    storageBucket: 'pill-buddy-cpe-nnovators.firebasestorage.app',
    measurementId: 'G-9D950X5KSM',
  );
}
